name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set version
        run: echo "VERSION=latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/homewarden:${{ env.VERSION }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/homewarden:${{ env.VERSION }}
